<?php

/**
 * @file
 * Install file for the upgrade_check module.
 */

/**
 * Implements hook_uninstall().
 */
function upgrade_check_uninstall() {
  $variables = array(
    UPGRADE_CHECK_JSON_PATH,
    UPGRADE_CHECK_SETTINGS_FORM,
    UPGRADE_CHECK_REPLACE_ENTITY_NAME,
    UPGRADE_CHECK_SALT_FIELD_NAME,
    UPGRADE_CHECK_DATA_METHOD,
  );
  foreach ($variables as $variable) {
    variable_del($variable);
  }
}
